### ISSUE TITLE
handle rotation in a more elegant way?

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_MagTag#13]
for now this works, if you set the rotation thru the magtag.display you need to recreate the magtag object... or maybe this is fine!
```
import time
import board
import terminalio
from adafruit_magtag.magtag import MagTag

board.DISPLAY.rotation = 270
magtag = MagTag()

magtag.add_text(
    text_font=terminalio.FONT,
    text_position=(
        magtag.graphics.display.width // 2,
        magtag.graphics.display.height // 2,
    ),
    text_anchor_point=(0.5, 0.5),
    text_scale=3,
)

if magtag.display.rotation in (90, 270):
    magtag.set_text("Hello World")
else:
    magtag.set_text("Hello\nWorld")
while True:
    pass
```

**Comment by makermelissa** [comment]
Now that board.DISPLAY is included in Magtag, I plan on removing the display driver init code which isn't being used at this point. Changing board.DISPLAY.rotation _should_ be the same as changing magtag.display.rotation, but perhaps it's not. I'll try some things next week when I start working on factoring out a portal base library. Maybe we need some kind of update function that handles it.

**Comment by ladyada** [comment]
it is the same but the display buffer uses the old dimensions, we need to update those

**Comment by makermelissa** [comment]
Ok, then maybe we can make a property that handles this, though that may or may not be a more elegant way.

**Comment by ladyada** [comment]
with deep sleep this may not be an issue anymore, we'll start over fresh on every run
