### ISSUE TITLE
Still drawing >50mA during time.sleep()

### ISSUE THREAD

**Issue by DaveVdE** [adafruit/Adafruit_CircuitPython_MagTag#20]
The plan was to have a new update downloaded every 60s and then put the MagTag to sleep saving battery, but I'm measuring a constant 50-100mA current draw even when doing nothing. 

I think the WiFi radio is to blame, but I can't figure out how to turn off the WiFi during sleep. How do I do this?

**Comment by dhalbert** [comment]
Real deep sleep is in progress. I just got it to work last night and will be checking the current draw today. It should be in a beta release soon. See https://github.com/adafruit/circuitpython/issues/2796, though the API is still evolving.

**Comment by DaveVdE** [comment]
Thank you, that was very helpful.
