### ISSUE TITLE
MagTag onboard NeoPixel brightness is not working

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_MagTag#21]
Attempting to set the brightness of the on-board NeoPixels using the MagTag NeoPixel object does not work. They are max brightness regardless of what the brightness is set to.

Tested setting the NeoPixel brightness using raw CircuitPython and the NeoPixel library, and it was successful (though there is a bug somewhere in which setting `brightness = 0` makes them max brightness - looking into where to file that bug as well).

**Comment by ladyada** [comment]
hi are you trying
```
# lights up!
magtag.peripherals.neopixels.brightness = 0.1
magtag.peripherals.neopixel_disable = False # turn on lights
magtag.peripherals.neopixels.fill(0x0F0F0F)
```

**Comment by kattni** [comment]
That works. Thank you.

Though I don't understand why it's required - it defaults to `False` in the lib.

https://github.com/adafruit/Adafruit_CircuitPython_MagTag/blob/056ad75102a5b870ba3e046a9c5498aa4cd4c675/adafruit_magtag/peripherals.py#L47
