### ISSUE TITLE
My bmp make MagTag bootloop without message

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_MagTag#34]
If you take my pihole.bmp in a command like 'magtag.graphics.set_background("/bmps/pihole.bmp")' the MagTag Bootloop (without error message).

See https://github.com/dglaude/bootloop_MagTagLib for file.

Obviously, something is wrong in my BMP (and I would love to know what and any fix is welcome), but it should not bootloop without a message.

**Comment by slootsky** [comment]
how did you create your bmp?
If I take your .bmp , load it into mspaint and save it again, I get a file with the same size, and the same first 27 bytes, but then there are small variations for about the next 80 bytes, and then the rest of the files are identical.
I didn't try loading my new bmp into a magtag to see if it bootlooped.

**Comment by dglaude** [comment]
I used MS paint on Windows 10, just because I don't have better for the moment.
To make sure I start with the right palette, I first loaded a working file using those 4 colors I need.
I guess I need to analyse with imagik or invest in better tools for bitmap file (asprite?).

**Comment by dglaude** [comment]
I believe that Windows 10 Paint does put some "color space" information in the file.
When opening the file in GIMP and saving without that color space information, the file become readable...
I should work on my workflow, but that saved the day for me.

**Comment by makermelissa** [comment]
Gotcha. I'll see if maybe there's something that can be checked so at least you know it's an invalid bitmap.

**Comment by makermelissa** [comment]
Since it uses OnDiskBitmap, this may have to be something that's addressed at the CircuitPython level.

**Comment by hugodahl** [comment]
I just tried this on my MagTag, with both 6.1.0 release and 6.2.0-b4 in both the default English build, as well as French.

I used both your linked .bmp file as well as the "digikey.bmp" file which was originally included (mine came in an Adabox).

Are you still experiencing this issue with either this file or a different one, @dglaude?

**Comment by makermelissa** [comment]
Closing due to lack of response. We can always reopen this.
