### ISSUE TITLE
EPaperDisplay object cannot assign attribute 'rotation'

### ISSUE THREAD

**Issue by cjoh** [adafruit/Adafruit_CircuitPython_MagTag#44]
```
# MagTag Hello World

import time
from adafruit_magtag.magtag import MagTag

magtag = MagTag()
magtag.add_text(
    text_position=(
        50,
        (magtag.graphics.display.height // 2) - 1,
    ),
    text_scale=3,
)
 
magtag.set_text("Hello World")
```

This gives me an AttributeError on line 57 in __init__ from adafruit_magtag/graphics.py

**Comment by lemonkey** [comment]
Also seen with the spacex demo code https://learn.adafruit.com/spacex-next-launch-display-with-adafruit-magtag/code

**Comment by FoamyGuy** [comment]
Can you post the contents of boot_out.txt? 

Maybe try updating to the latest version of Circuit Python on your device, I think that rotation was added very recently.

**Comment by cjoh** [comment]
Updating to the 12/16 build of circuitpython worked.

**Comment by lemonkey** [comment]
Confirmed latest CircuitPython from today works.

**Comment by FoamyGuy** [comment]
Thank you! closing this for now.
