### ISSUE TITLE
Magtag screen won't update

### ISSUE THREAD

**Issue by bdsvac** [adafruit/Adafruit_CircuitPython_MagTag#45]
The magtag is stuck on the Digi-Key screen from the factory. Using the latest:  adafruit-circuitpython-adafruit_magtag_2.9_grayscale-en_US-20201216-f2204d7.uf2 from S3, using https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/download/20201216/adafruit-circuitpython-bundle-6.x-mpy-20201216.zip bundle. Used esp-idf to write bootloader: https://learn.adafruit.com/adafruit-magtag/install-uf2-bootloader.

The following code:

import time
import displayio
time.sleep(2)
print('0')
time.sleep(2)
from adafruit_magtag.magtag import MagTag
time.sleep(2)
print("1")
magtag = MagTag()
time.sleep(2)
print("2")
magtag.add_text(
    text_position=(
        50,
        (magtag.graphics.display.height // 2) - 1,
    ),
    text_scale=3,
)
print("3")
try:
    magtag.set_text("Hello World")
    pass
except:
    print("Really bad thing happened.")
print("4")

outputs:
0
1
2
3

It never outputs "4" or "Really bas thing happened."

**Comment by ladyada** [comment]
how about trying the 'all in one demo' file here
https://learn.adafruit.com/adafruit-magtag/shipping-demo
download the UF2 and drag it onto the magtag, that will determine where the issue lies

**Comment by bdsvac** [comment]
@ladyada Running the demo, the LED's, buttons, and speaker work. In the console I am seeing light sensor and accelerometer data, but the screen is still displaying the Digi-Key logo from the factory.
![PXL_20201216_181601173](https://user-images.githubusercontent.com/8561979/102389358-9dcd7a00-3f98-11eb-92c6-0c4a4315478d.jpg)

**Comment by ladyada** [comment]
turn off, flip over the board and verify the display is well-seated in the connector. maybe reseat it.

**Comment by bdsvac** [comment]
@ladyada that has been done with no change in result. The Digi-Key logo is still displayed.
![PXL_20201216_182108650](https://user-images.githubusercontent.com/8561979/102389892-627f7b00-3f99-11eb-972d-4f304890d850.jpg)

**Comment by ladyada** [comment]
ok email support@adafruit for a replacement. any other issues, post in the adafruit forums please
