### ISSUE TITLE
Unable to play WAV file

### ISSUE THREAD

**Issue by mdwelsh** [adafruit/Adafruit_CircuitPython_MagTag#52]
Howdy! I am using this library to try to play a WAV file on the MagTag board using CircuitPython 6.1.0. I am trying to figure out what would need to be done to make this work.

The history of commits to peripherals.py has me somewhat confused. Initially there seemed to be a `play_wav_file` function available in a previous version of the library, which used `audioio`. However, audioio does not seem to be available for this board. Was this code ever used/tested or was it just wishful thinking on my part that I could use it? :-)

https://github.com/adafruit/Adafruit_CircuitPython_MagTag/blob/14d7b126d3cfeb325c9fc32eaca14090d4f057ab/adafruit_magtag/peripherals.py#L83

I am having difficulty understanding what `play_tone` is actually doing. If I try to call `simpleio.tone(board.SPEAKER, 300, 0.2)` directly, no sound occurs (but there is no exception). However, once I create my own `DigitalInOut` for the `board.SPEAKER` pin and invoke `simpleio.tone`, I get the dreaded `NameError: name 'AudioOut' is not defined` error.

```
>>> from digitalio import DigitalInOut, Direction
>>> speaker = DigitalInOut(board.SPEAKER)
>>> speaker.direction = Direction.OUTPUT
>>> speaker.value = True
>>> simpleio.tone(board.SPEAKER, 300, 0.2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simpleio.py", line 82, in tone
NameError: name 'AudioOut' is not defined
```

This is really confusing, since it only seems to occur once I set up DigitalInOut. And tones play fine if I use:

```
magtag.peripherals.play_tone(300, 0.1)
```

This suggests that the version of this library I have on my board (which came shipped with ADABOX 017) does not exactly match what I'm seeing in this repo. Any tips or suggestions on how to unlock the FULL AUDIO POTENTIAL of this amazing device? Thank you!

**Comment by ladyada** [comment]
yah DAC/WAV playback doesnt work on the ESP32S2 at this time, you can make beeps with the buzzer - using a PWM output (there's some magtag examples). you cannot (yet) play audio clips or waveforms

**Comment by mdwelsh** [comment]
Thanks for the quick reply. Is this a software limitation or a hardware one? If it's software I might be able to fix it.

I'm still confused why trying to use `simpleio.tone()` directly gives this error. Is there a way to determine which version of the MagTag library is in use in CP 6.1.0?

**Comment by ladyada** [comment]
its software, nontrivial to fix! https://github.com/adafruit/circuitpython/issues/3898
try deleteing and reinstalling all libraries - use the magtag library to make tones
if you're still having issues please post in the adafruit forum :)

**Comment by purepani** [comment]
Is  this possible now that the linked issue is closed @ladyada
