### ISSUE TITLE
adafruit_portalbase Dependency Error

### ISSUE THREAD

**Issue by sergiomoraes** [adafruit/Adafruit_CircuitPython_MagTag#53]
### Context

* I'm following the [MagTag Quotes Board](https://learn.adafruit.com/magtag-showerthoughts/code-the-magtag-quotes) guide.

* This is my code: [MagTag Quotes Board - Sergio](https://paste.debian.net/plainh/a3e209a7)

* These are the libraries added to my MagTag board:

![mag_tag_libs](https://user-images.githubusercontent.com/21162065/107563590-1f571800-6b96-11eb-9834-edfe9cea37ed.png)

### Expected behavior

1. MagTag displays quote message
2. MagTag goes into "deep sleep" for an hour
3. MagTag wakes up and refreshes quote message

### Actual behavior

1. MagTag displays quote message
2. MagTag refreshes and display _error_ message
![magtag_error](https://user-images.githubusercontent.com/21162065/107564622-81644d00-6b97-11eb-834d-38e78911e220.jpg)

---

I believe I'm not missing any libraries and my code is correct, but I could be wrong. Any help would be appreciated.

**Comment by makermelissa** [comment]
Make sure your libraries are updated. That particular function is in PortalBase: https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/main/adafruit_portalbase/__init__.py#L304

**Comment by makermelissa** [comment]
Since that function has been in PortalBase from the beginning, I suspect you may be using an older version of the MagTag library that didn't use PortalBase.

**Comment by sergiomoraes** [comment]
I downloaded the newest bundle and replaced the libs in my MagTag just to be sure.
Unfortunately, that resulted in a different error message.

My best bet is probably to start from the beginning to find out where things went wrong.

Thank you!

**Comment by makermelissa** [comment]
You may also want to check that you're using the latest version of CircuitPython, but I wouldn't imagine it would result in this particular error. You can download from https://circuitpython.org.

**Comment by sergiomoraes** [comment]
Thank you for the help and advice. I'll try to troubleshoot my setup.
