### ISSUE TITLE
how to set tone volume

### ISSUE THREAD

**Issue by stephanschulz** [adafruit/Adafruit_CircuitPython_MagTag#66]
The MagTag is great but the buzzer sound is very loud. 
Is there an option to set the volume directly or make a change to one of the libraries?

Thanks for any advice.

**Comment by makermelissa** [comment]
Currently this is just a wrapper for the `tone()` function in simpleio (https://github.com/adafruit/Adafruit_CircuitPython_SimpleIO/blob/main/simpleio.py#L37-L69). The tone function doesn't provide any parameters for setting the volume (amplitude), but I wonder if it could be added.

**Comment by makermelissa** [comment]
Unfortunately, this is a square wave with no amplitude control, so there doesn't appear to be a way to add this.
