### ISSUE TITLE
NeoPixels can't be disabled

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_MagTag#75]
@foamyguy and https://forums.adafruit.com/viewtopic.php?f=60&t=186080 report NeoPixel disabling no (no longer/) works.

Example:
```py
magtag.peripherals.neopixel_disable = False
magtag.peripherals.neopixels.fill((100, 0, 0))
time.sleep(2)
print("disabling neopixels")
magtag.peripherals.neopixel_disable = True
magtag.peripherals.neopixels.fill((0, 0, 100))
```
Pixels still turn blue.

**Comment by FoamyGuy** [comment]
A bit more troubleshooting reveals that when the library attempts to initialize the DigitalInOut for the `NEOPIXEL_POWER` pin the system believes that `NEOPIXEL_POWER_INVERTED` is already in use. The code from here:
https://github.com/adafruit/Adafruit_CircuitPython_MagTag/blob/e1e6a636abd7e96974c19d302cd76ef373169bb6/adafruit_magtag/peripherals.py#L47-L52

Is raising and catching the error. I added `raise e` into that except block to verify and I can see the traceback:
```
Traceback (most recent call last):
  File "code.py", line 109, in <module>
  File "/lib/adafruit_magtag/magtag.py", line 102, in __init__
  File "/lib/adafruit_magtag/peripherals.py", line 54, in __init__
  File "/lib/adafruit_magtag/peripherals.py", line 49, in __init__
ValueError: NEOPIXEL_POWER_INVERTED in use
```

**Comment by FoamyGuy** [comment]
I have also found that bypassing the library and directly handling the NEOPIXEL and `NEOPIXEL_POWER` pins does work as expected. With the following code we see the red light and the neopixels are turned off so we never see the blue light:
```py
import time
import board
import neopixel
from digitalio import DigitalInOut, Direction

neopixel_disable = DigitalInOut(board.NEOPIXEL_POWER)
neopixel_disable.direction = Direction.OUTPUT
neopixel_disable.value = False

pixel_pin = board.NEOPIXEL

num_pixels = 4

ORDER = neopixel.GRB

pixels = neopixel.NeoPixel(
    pixel_pin, num_pixels, brightness=0.1, auto_write=False, pixel_order=ORDER
)

pixels.fill((255, 0, 0))
pixels.show()
time.sleep(1)
neopixel_disable.value = True


pixels.fill((0, 0, 255))
pixels.show()
time.sleep(1)
```

**Comment by FoamyGuy** [comment]
I think I understand the root of this issue. the `neopixel` library is initializing `NEOPIXEL_POWER` itself now here:

https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/blob/9ca3bf00c6a2dd1de2d315a3b952a381d720aa7d/neopixel.py#L129-L143

This means it's already in use by the time the MagTag library tries to initialize it. 

With my other direct pin example above I initialized the power pin first so it was in use when neopixel tried to initialize it and it silently catches that error and moves on.
