### ISSUE TITLE
Battery reads much higher and narrower than expected

### ISSUE THREAD

**Issue by pianohacker** [adafruit/Adafruit_CircuitPython_MagTag#84]
With a 4.2-3.7V LiPo battery plugged in, `MagTag().peripherals.battery` reads 5.3-5.2V.

**Comment by dhalbert** [comment]
Originally reported in https://github.com/adafruit/circuitpython/issues/6148, fix in progress in https://github.com/adafruit/circuitpython/pull/6246. This is a core CircuitPython issue.

**Comment by pianohacker** [comment]
Thanks for the quick response. Is there any workaround?

**Comment by dhalbert** [comment]
Try waiting at least one second before reading the battery voltage after creating the `MagTag()` object. Are you calling it immediately?

**Comment by dhalbert** [comment]
More precisely, you can call it once, then wait at least one second and call it again (this is only the first time):
```py
dafruit CircuitPython 7.2.4 on 2022-03-31; Adafruit MagTag with ESP32S2
>>> 
>>> from adafruit_magtag.magtag import MagTag
>>> m = MagTag()
>>> m.peripherals.battery
5.33599
>>> m.peripherals.battery
4.28992
```

**Comment by pianohacker** [comment]
Thanks, that works. Why are the two reads necessary, no matter how far apart the two reads are?
