### ISSUE TITLE
Voltage values seem questionable

### ISSUE THREAD

**Issue by timwoj** [adafruit/Adafruit_CircuitPython_MagTag#88]
The documentation says that I can retrieve the current voltage from the battery with `magtag.peripherals.battery`. Retrieving that value gives something back that seems non-sensical to me. For example, my magtag currently says that the battery is returning 414729 volts.

**Comment by timwoj** [comment]
Never mind, I see https://github.com/adafruit/Adafruit_CircuitPython_MagTag/issues/84. Closing this one as a dupe.

**Comment by dhalbert** [comment]
I think there may be a solution to this by adjusting the reset state of the pin. I've transfered the original library issue to https://github.com/adafruit/circuitpython/issues/6631.
